import { ERRORS_CODES } from '@errors/types';

export enum SOCKET_ERRORS {
  CREATE_FAILED = 'ERR_SOCKET_001',
  GET_FAILED = 'ERR_SOCKET_002',
  ADD_INTERFACE = 'ERR_SOCKET_003',
}

export enum DECODE_ERRORS {
  HEADER_SIZE = 'ERR_DECODE_001',
  NAME_OVERFLOW = 'ERR_DECODE_002',
  NAME_TOO_LONG = 'ERR_DECODE_003',
  INVALID_POINTER = 'ERR_DECODE_004',
  INVALID_NAME = 'ERR_DECODE_005',
}
export type ErrorCodes = ERRORS_CODES & SOCKET_ERRORS & DECODE_ERRORS;
