import { MDNS_RESOURCE_RECORDS_TYPES } from './types';

export const MDNS_RESOURCE_RECORDS_ORDER = [
  MDNS_RESOURCE_RECORDS_TYPES.QUESTION,
  MDNS_RESOURCE_RECORDS_TYPES.ANSWER,
  MDNS_RESOURCE_RECORDS_TYPES.AUTHORITY,
  MDNS_RESOURCE_RECORDS_TYPES.ADDITIONAL,
];

export const MDNS_HEADER_LENGTH = 0x0c;
